### ISSUE TITLE
Jar releases

### ISSUE THREAD

**Issue by kiselev-dv** [dwins/mapnik2geotools#44]
Is it possible to create releases with executable java jars?

sbt is a greate tool for development, but if you want just use it, it's much more simple to use jar files with included scala-library

**Comment by dwins** [comment]
Sorry, almost didn't see this as my email notifications haven't been working for the past couple of days.  The SBT configuration is set up to use the sbt-assembly plugin so all that is needed to create a self-contained executable jar is `sbt assembly`.  I should probably add notes to the README about building and using that... 

Anyway I had a download for this a while ago but it was lost when Github changed the way artifacts were handled.  I've just created a release using the newer system so you should be able to get that. https://github.com/dwins/mapnik2geotools/releases/tag/v0.1

**Comment by kiselev-dv** [comment]
Thank you @dwins I've got it
